apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-cicd-app
  name: web-cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-cicd-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-cicd-app
    spec:
      containers:
        - image: ghcr.io/haryu-ta/cicd-for-kubernetes:023a6dde4a12de5e376ed8507841c8b675a75229
          name: web-cicd-app
          envFrom:
            - configMapRef:
                name: web-cicd-app
            - secretRef:
                name: web-cicd-app
          resources: {}
status: {}
##
