apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-cicd-app
  name: web-cicd-app
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-cicd-app
  type: ClusterIP
status:
  loadBalancer: {}
