apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-cicd-app
  namespace: argocd
  finalizers: # Cascading Deletion https://argo-cd.readthedocs.io/en/stable/user-guide/app_deletion/#about-the-deletion-finalizer
     - resources-finalizer.argocd.argoproj.io
spec:
  project: web-cicd
  source:
    repoURL: https://github.com/haryu-ta/cicd-for-kubernetes.git
    path: manifests/web-cicd
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
