name: deploy
run-name: ${{ github.actor }} is testing
on:
    push:
      branches:
        - 'main'
      paths:
        - '.github/workflows/**'

jobs:
  Exec-Java-Push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
        - run: echo "EventName is ${{ github.event_name }}"
        - run: echo "Running os is ${{ runner.os }}"
        - run: echo "Branch is ${{ github.ref }}"
        - name: Checkout Repository Code
          uses: actions/checkout@v4
        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ghcr.io/${{ github.repository }}
        - name: Login to Github Container Resistory
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: List Files in the Repository
          run: |
            ls -l ${{ github.workspace }}  
        - name: Get Commit Message
          run: |
            echo ${{ github.event.head_commit.message}}
            echo ${{ github.sha }}
        - name: Build and Push
          uses: docker/build-push-action@v5
          with:
            context: .
            platforms: linux/arm64
            push: true
            tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
            labels: ${{ steps.meta.outputs.labels }}
        - run: echo "The Repository is ${{ github.repository }}"
        - run: echo "This Job's status is ${{ job.status}}"
      

  Update-kubernetes-manifest:
    runs-on: ubuntu-latest
    needs: [Exec-Java-Push]
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
      - name: Update Image Sample
        env:
          IMAGE_TAG_NAME: ghcr.io/${{ github.repository }}:${{ github.sha }}
        run: |
          yq -i "(.spec.template.spec.containers[] | select(.name == \"web-cicd-app\")).image = \"$IMAGE_TAG_NAME\""  manifest/web-cicd/deployment.yaml
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          draft: true
          title: "Update web-cicd"
          body: |
            # Changes
            - Update `web-cicd` image to ghcr.io/${{ github.repository }}:${{ github.sha }}