name: deploy
run-name: ${{ github.actor }} is testing
on:
    push:
      branches:
        - 'main'

jobs:
  Exec-Java-Push:
    runs-on: ubuntu-latest
    steps:
        - run: echo "EventName is ${{ github.event_name }}"
        - run: echo "Running os is ${{ runner.os }}"
        - run: echo "Branch is ${{ github.ref }}"
        - name: Checkout Repository Code
          uses: actions/checkout@v4
        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ghcr.io/${{ github.repository }}
        - name: Login to Github Container Resistory
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and Push
          uses: docker/build-push-action@v5
          with:
            context: src
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
        - run: echo "The Repository is ${{ github.repository }}"
        - run: echo "This Job's status is ${{ job.status}}"
        - name: List Files in the Repository
          run: |
            ls -l ${{ github.workspace }}
        # -uses: actions/setup-python@v2
        # -uses: pre-commit/action@v2.0.0        